In [1]:
# Import libraries for case study

import pandas as pd
import numpy as np
import datetime
import os

print("Libraries imported successfully")

Libraries imported successfully


In [32]:
# Import data frames from January - December

jan_2021 = pd.read_csv (r"C:\Users\madib\Desktop\Case Study 1\202101-divvy-tripdata.csv")
feb_2021 = pd.read_csv (r"C:\Users\madib\Desktop\Case Study 1\202102-divvy-tripdata.csv")
mac_2021 = pd.read_csv (r"C:\Users\madib\Desktop\Case Study 1\202103-divvy-tripdata.csv")
apr_2021 = pd.read_csv (r"C:\Users\madib\Desktop\Case Study 1\202104-divvy-tripdata.csv")
may_2021 = pd.read_csv (r"C:\Users\madib\Desktop\Case Study 1\202105-divvy-tripdata.csv")
jun_2021 = pd.read_csv (r"C:\Users\madib\Desktop\Case Study 1\202106-divvy-tripdata.csv")
jul_2021 = pd.read_csv (r"C:\Users\madib\Desktop\Case Study 1\202107-divvy-tripdata.csv")
aug_2021 = pd.read_csv (r"C:\Users\madib\Desktop\Case Study 1\202108-divvy-tripdata.csv")
sep_2021 = pd.read_csv (r"C:\Users\madib\Desktop\Case Study 1\202109-divvy-tripdata.csv")
oct_2021 = pd.read_csv (r"C:\Users\madib\Desktop\Case Study 1\202110-divvy-tripdata.csv")
nov_2021 = pd.read_csv (r"C:\Users\madib\Desktop\Case Study 1\202111-divvy-tripdata.csv")
dec_2021 = pd.read_csv (r"C:\Users\madib\Desktop\Case Study 1\202112-divvy-tripdata.csv")

In [33]:
#Merge the data frames becoming a dataset

dataset = [jan_2021,feb_2021,mac_2021,apr_2021,may_2021,jun_2021,aug_2021,sep_2021,oct_2021,nov_2021,dec_2021]
dataset = pd.concat(dataset)

In [34]:
dataset

ride_id  rideable_type        started_at          ended_at  \
0       E19E6F1B8D4C42ED  electric_bike   23/1/2021 16:14   23/1/2021 16:24   
1       DC88F20C2C55F27F  electric_bike   27/1/2021 18:43   27/1/2021 18:47   
2       EC45C94683FE3F27  electric_bike   21/1/2021 22:35   21/1/2021 22:37   
3       4FA453A75AE377DB  electric_bike    7/1/2021 13:31    7/1/2021 13:42   
4       BE5E8EB4E7263A0B  electric_bike    23/1/2021 2:24    23/1/2021 2:24   
...                  ...            ...               ...               ...   
247535  847431F3D5353AB7  electric_bike  12/12/2021 13:36  12/12/2021 13:56   
247536  CF407BBC3B9FAD63  electric_bike   6/12/2021 19:37   6/12/2021 19:44   
247537  60BB69EBF5440E92  electric_bike    2/12/2021 8:57    2/12/2021 9:05   
247538  C414F654A28635B8  electric_bike   13/12/2021 9:00   13/12/2021 9:14   
247539  37AC57E34B2E7E97   classic_bike   13/12/2021 8:45   13/12/2021 8:49   

                 start_station_name start_station_id  \
0        California Ave & Cortez St            17660   
1        California Ave & Cortez St            17660   
2        California Ave & Cortez St            17660   
3        California Ave & Cortez St            17660   
4        California Ave & Cortez St            17660   
...                             ...              ...   
247535        Canal St & Madison St            13341   
247536        Canal St & Madison St            13341   
247537        Canal St & Madison St            13341   
247538       Lawndale Ave & 16th St              362   
247539  Michigan Ave & Jackson Blvd     TA1309000002   

                end_station_name end_station_id  start_lat  start_lng  \
0                            NaN            NaN  41.900341 -87.696743   
1                            NaN            NaN  41.900333 -87.696707   
2                            NaN            NaN  41.900313 -87.696643   
3                            NaN            NaN  41.900399 -87.696662   
4                            NaN            NaN  41.900326 -87.696697   
...                          ...            ...        ...        ...   
247535                       NaN            NaN  41.882289 -87.639752   
247536  Kingsbury St & Kinzie St   KA1503000043  41.882123 -87.640053   
247537   Dearborn St & Monroe St   TA1305000006  41.881956 -87.639955   
247538                       NaN            NaN  41.860000 -87.720000   
247539   Dearborn St & Monroe St   TA1305000006  41.877850 -87.624080   

          end_lat    end_lng member_casual  
0       41.890000 -87.720000        member  
1       41.900000 -87.690000        member  
2       41.900000 -87.700000        member  
3       41.920000 -87.690000        member  
4       41.900000 -87.700000        casual  
...           ...        ...           ...  
247535  41.890000 -87.610000        casual  
247536  41.889106 -87.638862        member  
247537  41.880254 -87.629603        member  
247538  41.850000 -87.710000        member  
247539  41.881320 -87.629521        member  

[4772653 rows x 13 columns]

In [35]:
#Inspecting at the dataset info 

dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4772653 entries, 0 to 247539
Data columns (total 13 columns):
 #   Column              Dtype  
---  ------              -----  
 0   ride_id             object 
 1   rideable_type       object 
 2   started_at          object 
 3   ended_at            object 
 4   start_station_name  object 
 5   start_station_id    object 
 6   end_station_name    object 
 7   end_station_id      object 
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       object 
dtypes: float64(4), object(9)
memory usage: 509.8+ MB


In [36]:
#Looking for null values within the dataset

dataset.isnull().sum()

ride_id                    0
rideable_type              0
started_at                 0
ended_at                   0
start_station_name    603546
start_station_id      603544
end_station_name      646012
end_station_id        646012
start_lat                  0
start_lng                  0
end_lat                 4040
end_lng                 4040
member_casual              0
dtype: int64

In [37]:
#Remove the nulls from the dataset

dataset = dataset.dropna(how='any', axis=0)

print('Null values remove successfully')

dataset.isnull().sum()

Null values remove successfully


ride_id               0
rideable_type         0
started_at            0
ended_at              0
start_station_name    0
start_station_id      0
end_station_name      0
end_station_id        0
start_lat             0
start_lng             0
end_lat               0
end_lng               0
member_casual         0
dtype: int64

In [38]:
#Looking for any duplicates row

dataset.duplicated().any()

False

In [39]:
#Change the data types

pd.options.mode.chained_assignment = None

dataset["started_at"] = pd.to_datetime(dataset["started_at"])
dataset["ended_at"] = pd.to_datetime(dataset["ended_at"])

dataset.info()

C:\Users\madib\AppData\Local\Temp\ipykernel_20800\453992575.py:3: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  dataset["started_at"] = pd.to_datetime(dataset["started_at"])
C:\Users\madib\AppData\Local\Temp\ipykernel_20800\453992575.py:4: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  dataset["ended_at"] = pd.to_datetime(dataset["ended_at"])


<class 'pandas.core.frame.DataFrame'>
Index: 3895981 entries, 9 to 247539
Data columns (total 13 columns):
 #   Column              Dtype         
---  ------              -----         
 0   ride_id             object        
 1   rideable_type       object        
 2   started_at          datetime64[ns]
 3   ended_at            datetime64[ns]
 4   start_station_name  object        
 5   start_station_id    object        
 6   end_station_name    object        
 7   end_station_id      object        
 8   start_lat           float64       
 9   start_lng           float64       
 10  end_lat             float64       
 11  end_lng             float64       
 12  member_casual       object        
dtypes: datetime64[ns](2), float64(4), object(7)
memory usage: 416.1+ MB


In [40]:
#Creating new metrics for better insights from dataset

dataset["trip_duration"] = dataset["ended_at"] - dataset["started_at"]
dataset["trip_duration"] = pd.to_numeric(dataset["trip_duration"])/6e+10

In [41]:
dataset["trip_duration"].describe(include = "all")

count    3.895981e+06
mean     2.138782e+01
std      1.750757e+02
min     -5.600000e+01
25%      7.000000e+00
50%      1.200000e+01
75%      2.200000e+01
max      5.594400e+04
Name: trip_duration, dtype: float64

In [42]:
# removing outliers by creating filters

outliers_trip_duration = (dataset["trip_duration"] < 1) | (dataset["trip_duration"] > 480)
outliers_trip_duration.value_counts()

trip_duration
False    3861766
True       34215
Name: count, dtype: int64

In [43]:
# delete conflicting values

dataset.drop(dataset.index[outliers_trip_duration], inplace = True)

In [44]:
# getting the corresponding linear distances in meters using Numpy Library function

dataset["trip_distance"] = np.sqrt(((dataset["end_lat"] - dataset["start_lat"])**2) + ((dataset["end_lng"] - dataset["start_lng"])**2))
dataset["trip_distance"] = dataset["trip_distance"] * 111.139

In [45]:
dataset["start_hour"] = dataset["started_at"].dt.hour
dataset["start_hour"].unique()

array([19, 15, 10, 11,  7,  8, 13,  9, 21, 20,  0, 16, 17, 22, 14, 18, 12,
       23,  1,  6,  2,  4,  5,  3])

In [46]:
dataset["start_day_num"] = dataset["started_at"].dt.dayofweek
day_dict = {0:"Sunday", 1:"Monday", 2:"Tuesday", 3:"Wednesday", 4:"Thursday", 5:"Friday", 6:"Saturday"}
dataset["start_day_name"]= dataset["start_day_num"].apply(lambda y:day_dict[y])

In [47]:
dataset["weekend"] = np.where(dataset["start_day_num"] > 5, True, False)

In [48]:
# adding more columns such as start_month and start_year from datetime library

dataset['start_month_num'] = dataset['started_at'].dt.month
dataset["start_month_num"].unique()

array([ 1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 12])

In [49]:
month_dict = {1:"January", 2:"February", 3:"March", 4:"April", 5:"May", 6:"June", 7:"July", 8:"August", 9:"September", 10:"October", 11:"November", 12:"December"}
dataset["start_month_name"]= dataset["start_month_num"].apply(lambda y:month_dict[y])
dataset["start_month_name"].unique()

array(['January', 'February', 'March', 'April', 'May', 'June', 'August',
       'September', 'October', 'November', 'December'], dtype=object)

In [50]:
dataset['start_year'] = dataset['started_at'].dt.year
dataset["start_year"].unique()

array([2021])

In [51]:
dataset.rename(columns = {'member_casual': 'user_type'}, inplace=True)

In [52]:
# View the dataset

dataset

ride_id  rideable_type          started_at  \
9       B9F73448DFBE0D45   classic_bike 2021-01-24 19:15:00   
11      57C750326F9FDABE  electric_bike 2021-01-09 15:28:00   
12      4D518C65E338D070  electric_bike 2021-01-09 15:28:00   
13      9D08A3AFF410474D   classic_bike 2021-01-24 15:56:00   
14      49FCE1F8598F12C6  electric_bike 2021-01-22 15:15:00   
...                  ...            ...                 ...   
247528  E06135F650553F21  electric_bike 2021-12-07 15:55:00   
247532  8DF0DBB049906332  electric_bike 2021-12-01 16:50:00   
247536  CF407BBC3B9FAD63  electric_bike 2021-12-06 19:37:00   
247537  60BB69EBF5440E92  electric_bike 2021-12-02 08:57:00   
247539  37AC57E34B2E7E97   classic_bike 2021-12-13 08:45:00   

                  ended_at           start_station_name start_station_id  \
9      2021-01-24 19:22:00   California Ave & Cortez St            17660   
11     2021-01-09 15:37:00   California Ave & Cortez St            17660   
12     2021-01-09 15:37:00   California Ave & Cortez St            17660   
13     2021-01-24 16:07:00   California Ave & Cortez St            17660   
14     2021-01-22 15:36:00   California Ave & Cortez St            17660   
...                    ...                          ...              ...   
247528 2021-12-07 16:00:00        Canal St & Madison St            13341   
247532 2021-12-01 16:55:00        Canal St & Madison St            13341   
247536 2021-12-06 19:44:00        Canal St & Madison St            13341   
247537 2021-12-02 09:05:00        Canal St & Madison St            13341   
247539 2021-12-13 08:49:00  Michigan Ave & Jackson Blvd     TA1309000002   

                 end_station_name end_station_id  start_lat  start_lng  ...  \
9          Wood St & Augusta Blvd            657  41.900363 -87.696704  ...   
11         Wood St & Augusta Blvd            657  41.900374 -87.696688  ...   
12         Wood St & Augusta Blvd            657  41.900379 -87.696716  ...   
13         Wood St & Augusta Blvd            657  41.900363 -87.696704  ...   
14              Wells St & Elm St   KA1504000135  41.900373 -87.696790  ...   
...                           ...            ...        ...        ...  ...   
247528  Desplaines St & Kinzie St   TA1306000003  41.881372 -87.640042  ...   
247532  Desplaines St & Kinzie St   TA1306000003  41.881999 -87.639265  ...   
247536   Kingsbury St & Kinzie St   KA1503000043  41.882123 -87.640053  ...   
247537    Dearborn St & Monroe St   TA1305000006  41.881956 -87.639955  ...   
247539    Dearborn St & Monroe St   TA1305000006  41.877850 -87.624080  ...   

        user_type  trip_duration trip_distance  start_hour  start_day_num  \
9          member            7.0      2.726517          19              6   
11         casual            9.0      2.727283          15              5   
12         casual            9.0      2.730663          15              5   
13         casual           11.0      2.726517          15              6   
14         member           21.0      6.935098          15              4   
...           ...            ...           ...         ...            ...   
247528     casual            5.0      0.920661          15              1   
247532     casual            5.0      0.909298          16              2   
247536     member            7.0      0.787309          19              0   
247537     member            8.0      1.165987           8              3   
247539     member            4.0      0.717198           8              0   

        start_day_name  weekend start_month_num  start_month_name  start_year  
9             Saturday     True               1           January        2021  
11              Friday    False               1           January        2021  
12              Friday    False               1           January        2021  
13            Saturday     True               1           January        2021  
14            Thursday    False               1           January        

In [53]:
# Export the dataset into csv file using pandas library function

dataset.to_csv('cyclistic_dataset.csv', index=False)